#include <stdio.h>

void line()
{
    printf("----------------------------------\n");
}
void header(char *header)
{
    line();
    printf("%s\n", header);
    line();
}

void fahrenheitToCelsius()
{
    float fahr, celsius;
    float lower, upper, step;
    lower = 0;   /* lower limit of temperature scale */
    upper = 300; /* upper limit */
    step = 20;   /* step size */
    fahr = lower;
    header("Fahrenheit to Celsius Conversion");
    while (fahr <= upper)
    {
        celsius = 5 * (fahr - 32) / 9;
        // %6.2f is the precision formatting of a float value.
        printf("°F:%3.0f | °C:%6.2f\n", fahr, celsius);
        fahr = fahr + step;
    }
    line();
}

void celsiusToFahrenheit()
{
    float fahr, celsius;
    float lower, upper, step;
    lower = -40; /* lower limit of temperature scale */
    upper = 60;  /* upper limit */
    step = 5;    /* step size */
    celsius = lower;
    header("Celsius to Fahrenheit Conversion");
    while (celsius <= upper)
    {
        fahr = celsius * 9 / 5 + 32;
        printf("°C:%3.0f | °F:%6.2f\n", celsius, fahr);
        celsius = celsius + step;
    }
    line();
}

void betterConverter()
{
    float fahr;
    header("Fahrenheit to Celsius Conversion");
    for (fahr = 0; fahr <= 300; fahr = fahr + 20)
        printf("°F:%3.0f | °C:%6.2f\n", fahr, (5.0 / 9.0) * (fahr - 32));
    line();
    float celsius;
    header("Celsius to Fahrenheit Conversion");
    for (celsius = -60; celsius <= 60; celsius = celsius + 6)
        printf("°C:%3.0f | °F:%6.2f\n", celsius, (celsius * 9 / 5) + 32);
    line();
}

void backwardConverter()
{
    float fahr;
    header("Fahrenheit to Celsius Conversion");
    for (fahr = 300; fahr >= 0; fahr = fahr - 20)
        printf("°F:%3.0f | °C:%6.2f\n", fahr, (5.0 / 9.0) * (fahr - 32));
    line();
    float celsius;
    header("Celsius to Fahrenheit Conversion");
    for (celsius = 60; celsius >= -60; celsius = celsius - 6)
        printf("°C:%3.0f | °F:%6.2f\n", celsius, (celsius * 9 / 5) + 32);
    line();
}

void main()
{
    fahrenheitToCelsius();
    celsiusToFahrenheit();
    printf("\n Same output but generated by the for loop \n");
    betterConverter();
    printf("\n Now it is backwards! \n");
    backwardConverter();
}
